### ISSUE TITLE
GET method http://localhostlimesharp/ajax/stores?_=*  net::ERR_NAME_NOT_RESOLVED, while loading stockist page of limesharp extension in my project of Magento2.

### ISSUE THREAD

**Issue by vishalpawar-tudip** [ClaudiuCreanga/magento2-store-locator-stockists-extension#10]
Above problem shows json response null while ajax call and showing error at xhr.send() method.
Any help is really apprecible.

**Comment by ClaudiuCreanga** [comment]
http://localhostlimesharp/ajax/ is wrong url. how did you arrive at this value?

**Comment by parnanzio** [comment]
The problem is in [`view/frontend/web/js/limesharp_stockists.js`](https://github.com/ClaudiuCreanga/magento2-store-locator-stockists-extension/blob/master/src/view/frontend/web/js/limesharp_stockists.js#L50), you need to put a `/` before `config.moduleUrl`

**Comment by vishalpawar-tudip** [comment]
@ClaudiuCreanga  While loading this page url  'http://localhost/magento2/stockists', it only shows  'find a stockist' panel but not showing google map. Also I have added google map api key through admin panel of Magento2.

**Comment by vishalpawar-tudip** [comment]
Yes, I did it.  But not working and giving error as "Failed to load resource: the server responded with a status of 404 (Not Found)".
