### ISSUE TITLE
Error on function declaration after install another module

### ISSUE THREAD

**Issue by yosefkurniawan** [ClaudiuCreanga/magento2-store-locator-stockists-extension#11]
Hi,
This extension is awesome. Everything looks good until I install any other module, and got the following error:

> [Fri Mar 31 01:21:46.498511 2017] [proxy_fcgi:error] [pid 12907:tid 139916008716032] [client 128.199.213.16:53756] AH01071: Got error 'PHP message: PHP Fatal error:  Declaration of Limesharp\\Stockists\\Block\\Stockists\\Interceptor::getStoresForFrontend() must be compatible with Limesharp\\Stockists\\Block\\Stockists::getStoresForFrontend(): Limesharp\\Stockists\\Model\\ResourceModel\\Stores\\Collection in /var/www/releases/forcast/var/generation/Limesharp/Stockists/Block/Stockists/Interceptor.php on line 7

I dont know which one is wrong, this module or the other module. The other module is working properly, unfortunately the limesharp is not. Kindly help.

**Comment by ClaudiuCreanga** [comment]
Hi @yosefkurniawan 
Go to Limesharp\Stockists\Block\Stockists, at method getStoresForFrontend around line 150 and remove ": Collection". the word collection and the colons. I'll look into a proper fix.

**Comment by yosefkurniawan** [comment]
Hi @ClaudiuCreanga thanks for your reply.
Yes I did it and the error was gone for that line. But then the same error comes on another line, because most of the functions apparently have the same declaration way.
Ok, I will try to edit all of the function declaration for now and let's see if it work.

**Comment by ClaudiuCreanga** [comment]
I'm unable to replicate this one unfortunately.
