### ISSUE TITLE
Map settings not displaying in Magento 2.1.1 - Stores > Configuration > Stockists

### ISSUE THREAD

**Issue by Catlon** [ClaudiuCreanga/magento2-store-locator-stockists-extension#2]
On a vanilla **Magento 2.1.1** install, the **map customization settings are not displaying** as per the screen captures provided on the extension's page.

Also, the **map does not display in the front end** and there are no errors in the browser's DEV console.

**Comment by ClaudiuCreanga** [comment]
Hi,

Did you run through these steps?
composer update
php bin/magento setup:upgrade 
php bin/magento setup:static-content:deploy
php bin/magento cache:clean

You also have to get a google api key and insert it as the default key has reached it's quota. In my next update today I will insert the field in the admin.

**Comment by ClaudiuCreanga** [comment]
Ok, I've updated the extension so that you can insert Gmaps api keys in the admin. 
you can grab it with: composer require limesharp/stockists:1.0.16
Just tested it on a 2.1.1 installation and it is working fine. Let me know if there are still issues.

**Comment by Catlon** [comment]
Hello,
I had done the installation through the back-end.
Now i've just launched an upgrade through the back-end as well and I am getting the following message:

> Check Component Dependency
> We found conflicting component dependencies. Hide detail
> 
> Command "update" failed: Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - limesharp/stockists 1.0.15 requires php ~7.0.0 -> your PHP version (5.6.20) does not satisfy that requirement.
> - limesharp/stockists 1.0.15 requires php ~7.0.0 -> your PHP version (5.6.20) does not satisfy that requirement.
> - Installation request for limesharp/stockists 1.0.15 -> satisfiable by limesharp/stockists[1.0.15].
> 
> For additional assistance, see component dependency help .
> 
>

**Comment by Catlon** [comment]
Hello,
would you mind updating the Magento Marketplace version?
It is currently set to version 1.0.5
Thanks,
C.

**Comment by ClaudiuCreanga** [comment]
The marketplace version is in the process of being approved. Each version has to be approved and magento takes about 1 week to do it.

**Comment by Catlon** [comment]
Oh ok sorry about that.

**Comment by shefi** [comment]
@ClaudiuCreanga: So, without the version(s) which require PHP 7 it is NOT possible to change map settings!? I have installed version 1.0.6 and it does not have Map Settings.

**Comment by ClaudiuCreanga** [comment]
@shefi If you have 1.0.6 you have only a few settings available like title and description. Depending on which map setting you want to change you'll have to do it in the code.

**Comment by vishalpawar-tudip** [comment]
I installed limesharp store locator successfully, as well it is enabled also. But the Google map is not displayed in frontend view. Any help or solution is appreciable.
