### ISSUE TITLE
Individual store page doesn't work with custom route 

### ISSUE THREAD

**Issue by vphat28** [ClaudiuCreanga/magento2-store-locator-stockists-extension#20]
Hi
thank you for the best locator extension on magento 2 .

I'm facing an issue that i'm not sure if it's an issue or I misconfigured somethings. 
I can view the individual page under with url like this /stockists/view/index/id/3

but i can't do it by using custom route ( i set custom route in backend ). For example /store-locator/view/index/id/3 . It will return 404 page

The main page of locator still works fine under /store-locator/

Can you please advice how I can make single store page work with custom route?

**Comment by ClaudiuCreanga** [comment]
It should be under /store-locator/custom-url that you set in the backend. Not /view/index/id/3 . Best way to find out is to look into the url_rewrites table to find if something went wrong.

**Comment by vphat28** [comment]
oh so i have to set custom-url, it would be nicer if it can work without custom-url also. Thank you
