### ISSUE TITLE
Problem on save

### ISSUE THREAD

**Issue by tasselchof** [ClaudiuCreanga/magento2-store-locator-stockists-extension#25]
Fatal error: Uncaught TypeError: in_array() expects parameter 2 to be array, string given in /home/u1420/domains/new.ironlogic.bg/vendor/limesharp/stockists/src/Controller/Adminhtml/Stores/Save.php:171 Stack trace: #0 /home/u1420/domains/new.ironlogic.bg/vendor/limesharp/stockists/src/Controller/Adminhtml/Stores/Save.php(171): in_array('0', '1') #1 /home/u1420/domains/new.ironlogic.bg/var/generation/Limesharp/Stockists/Controller/Adminhtml/Stores/Save/Interceptor.php(24): Limesharp\Stockists\Controller\Adminhtml\Stores\Save->execute() #2 /home/u1420/domains/new.ironlogic.bg/vendor/magento/framework/App/Action/Action.php(102): Limesharp\Stockists\Controller\Adminhtml\Stores\Save\Interceptor->execute() #3 /home/u1420/domains/new.ironlogic.bg/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #4 /home/u1420/domains/new.ironlogic.bg/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dis in /home/u1420/domains/new.ironlogic.bg/vendor/limesharp/stockists/src/Controller/Adminhtml/Stores/Save.php on line 171

**Comment by ClaudiuCreanga** [comment]
Fixed by PR
