### ISSUE TITLE
on production server extension not working

### ISSUE THREAD

**Issue by navasim** [ClaudiuCreanga/magento2-store-locator-stockists-extension#27]
I have installed extension on local magento CE 2.2.2 it is working ( however had url issue for ajax request which fixed ). when i deployed the extension using composer , extension configurations area works but when i try to add stores it gives error :

Fatal error: Uncaught Error: Cannot instantiate interface Limesharp\Stockists\Api\StockistRepositoryInterface in /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111 Stack trace: #0 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Limesharp\\Stock...', Array) #1 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Limesharp\\Stock...') #2 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Limesharp\\Stock...') #3 /app/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Limesharp\\Stock...', Array) #4 /app/vendor/magento/framework/App/ActionFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Limesharp\\Stock...') #5 /app/vendor/magento/framework/App/Router/Base.php(297): Mage in /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111

**Comment by ClaudiuCreanga** [comment]
Hi. what version do you have installed?

**Comment by navasim** [comment]
magento EE 2.2.0

**Comment by ClaudiuCreanga** [comment]
No, I mean what version of this extension you have installed?

**Comment by navasim** [comment]
"version": "2.0.7", it is latest installed using composer

**Comment by ClaudiuCreanga** [comment]
Did you delete the cache in the var folder? I cannot replicate your issue with EE 2.2... It might be that you have other cache on your production server...

**Comment by navasim** [comment]
yes i did delete it too but not worked.

**Comment by harithasdckap** [comment]
@navasim , @ClaudiuCreanga, I am facing a similar problem. Is there any fix provided?

**Comment by ClaudiuCreanga** [comment]
@harithasdckap 
`Fatal error: Uncaught Error: Cannot instantiate interface 
`is a cache issue.
