### ISSUE TITLE
map doesn't render if url changed from stockists

### ISSUE THREAD

**Issue by gregdolder** [ClaudiuCreanga/magento2-store-locator-stockists-extension#29]
in the configuration update the url from `stockists` to `retailer-locator` the map then fails to render and throws a 404 jquery ajax error.

**Comment by ClaudiuCreanga** [comment]
Hi, This issue was solved in the latest release. What release are you using?

**Comment by gregdolder** [comment]
thanks for the quick response.  I'm using the version that currently installs via composer.  per the root composer.json it's `limesharp/stockists="^2.0"`, and per the composer.json in the vendor/limesharp/stockists folder it is `2.0.7`

**Comment by ClaudiuCreanga** [comment]
What's the ajax url that fails? Does it include stockists or retailer-locator?

**Comment by gregdolder** [comment]
404 failed to load resource  `<website>/retailer-locator/ajax/stores=_<id>`

**Comment by mserra** [comment]
Hello,

I got the same error on magento 2.2.2 with version 2.0.7

do you find any solution ?

**Comment by natecomp** [comment]
Has anyone figured out the fix for this?

**Comment by ClaudiuCreanga** [comment]
2.0.8 version released with the patch. Thanks @muhammadshakeel
