### ISSUE TITLE
Map does not load when custom URL path is defined in Admin

### ISSUE THREAD

**Issue by Sam-PUMP** [ClaudiuCreanga/magento2-store-locator-stockists-extension#3]
When choosing anything other then 'stockists' ie: store-finder, then the map graphic does not load.  However It works perfectly when stockists is used.

**Comment by ClaudiuCreanga** [comment]
this is a bug and will be fixed in a future version. you can fix it manually in view/frontend/web/js/limesharp_stockists.js and replace
	                var url = window.location.protocol+"//"+window.location.host + "/stockists" + '/ajax/stores';
 with 
	                var url = window.location.protocol+"//"+window.location.host + "/store-finder" + '/ajax/stores';

Let me know.

**Comment by Joe-Whitehead** [comment]
Hi,

I came across this error and applied your suggested action however I am still experiencing the issue.
Where it should appear: /find-a-retailer/ajax/stores?_=1480077664926 
but this shows a 404
If I navigate to /stockists/ajax/stores?_=1480077664926 
then it shows the file with the stockists.

**Comment by Sam-PUMP** [comment]
Yes @Joe-Whitehead  is right, it still does not work after solution is applied.  Thanks

**Comment by ClaudiuCreanga** [comment]
Does /find-a-retailer/ (or /store-finder) work and only the map doesn't work?

If that's the case then with that change it should work. Did you try redeploying and making sure the change is in pub/ folder?

**Comment by Joe-Whitehead** [comment]
@ClaudiuCreanga Yes the page works, but the map does not load.
I made your change, cleared the cache and all generated files, redeployed static content and it still continued to show this error.

**Comment by ErvinLlojku** [comment]
I confirm that the map works after updating the file `vendor/limesharp/stockists/src/view/frontend/web/js/limesharp_stockists.js`

**Comment by vishalpawar-tudip** [comment]
@ErvinLlojku Yes, I did it but showing error " GET http://localhost/magento2/stockists/ajax/stores?_=1488177647290 500 (Internal Server Error)".

Please help us to fix the problem.

**Comment by ClaudiuCreanga** [comment]
This has been fixed in 2.0

**Comment by axovel** [comment]
We can fix this issue easily by adding a url rewrite rule from Magento Admin. 
Go to Admin >> Marketing >> Url Rewrites and add a new Url Rewrite like below image

![image](https://user-images.githubusercontent.com/6186929/42579184-5f19c2ec-8545-11e8-8c90-9b59e956d7fc.png)
