### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by ClaudiuCreanga** [ClaudiuCreanga/magento2-store-locator-stockists-extension#30]
Looking for a maintainer to take control of this project and move it forward. There are new releases of magento2 and apparently some things stopped working, i.e. issue #29. As I no longer work with magento, I don't have time to debug the issue. Anyone interested, post your availability here.

**Comment by kumarbikash411** [comment]
yes i am ready to continue work on this but without your need it is not possible to continue

kumarbikash415@gmail.com

**Comment by kumarbikash411** [comment]
please add me in skyp: bikash.kumar986

**Comment by motou** [comment]
I can maintain this project since I will actively use this extension to develop projects.
