### ISSUE TITLE
Map shows inactive Stores

### ISSUE THREAD

**Issue by nykolak** [ClaudiuCreanga/magento2-store-locator-stockists-extension#36]
When you change Store status to inactive it still shows map pin for that Store. **execute()** in **Controller/Ajax/Stores.php** should be changed to return only active Stores.

**Comment by ClaudiuCreanga** [comment]
@nykolak are you using the 2.0.10 release?

**Comment by nykolak** [comment]
@ClaudiuCreanga yes

**Comment by ClaudiuCreanga** [comment]
@nykolak should be solved in 2.0.11
