### ISSUE TITLE
suporting M2 v 2.3 and php v 7.2

### ISSUE THREAD

**Issue by dsemyanovich** [ClaudiuCreanga/magento2-store-locator-stockists-extension#45]
Hello, the first want say thank for great job, very nice module!

And want ask about support for magento v2.3 and php v7.2?
I have tested some functionality on the same envirement and looks like all works fine, what do you think is possible add new tag with updating in composer.json?

Thanks!

**Comment by dsemyanovich** [comment]
Did it, check please when will have a time :)

**Comment by ClaudiuCreanga** [comment]
Thanks
