### ISSUE TITLE
Configurations missing

### ISSUE THREAD

**Issue by ps202** [ClaudiuCreanga/magento2-store-locator-stockists-extension#5]
In the configuration menu there are a lot of features missing.
See screenshot below.
![stockists](https://cloud.githubusercontent.com/assets/9308353/20453752/12678d1a-ae2f-11e6-9c89-e4e46006ed23.png)

**Comment by ClaudiuCreanga** [comment]
You must use the latest version (1.0.16) to see all configurations. Probably you are using v. 1.0.6. If you don't use php7 then you are stuck at that version as the newest requires php7.
