### ISSUE TITLE
Helper Folder Missing

### ISSUE THREAD

**Issue by cyblanceekhlas** [ClaudiuCreanga/magento2-store-locator-stockists-extension#8]
There is no Helper folder in src
Errors: 
1
[ReflectionException]                                         
  Class Limesharp\Stockists\Helper\ImageFactory does not exist 
2
[ReflectionException]                                         
  Class Limesharp\Stockists\Helper\ImageFactory does not exist
3
[RuntimeException]                                                           
  Source class "\Limesharp\Stockists\Helper\Image" for "Limesharp\Stockists\H  
  elper\ImageFactory" generation does not exist.

tell me where i can download it or you have any solution for it.

**Comment by ClaudiuCreanga** [comment]
Hi,

How did you install the extension and what version do you have?

Thanks!

**Comment by cyblanceekhlas** [comment]
Download from GitHub
after run command php bin/magento setup:di:compile and i found below errors
Errors:
1
[ReflectionException]
Class Limesharp\Stockists\Helper\ImageFactory does not exist
2
[ReflectionException]
Class Limesharp\Stockists\Helper\ImageFactory does not exist
3
[RuntimeException]
Source class "\Limesharp\Stockists\Helper\Image" for "Limesharp\Stockists\H
elper\ImageFactory" generation does not exist.

So also in src  GitHub there is no helper folder there.
Class call in Block ImageBuilder.php

**Comment by ClaudiuCreanga** [comment]
What versions did you download? please download the latest version from here https://github.com/ClaudiuCreanga/magento2-store-locator-stockists-extension/releases. It sounds to me that you downloaded the master branch.

**Comment by cyblanceekhlas** [comment]
ok
Thanks

**Comment by jimkar** [comment]
the Helper folders is still missing from all the versions on this site: https://github.com/ClaudiuCreanga/magento2-store-locator-stockists-extension/releases

**Comment by ClaudiuCreanga** [comment]
@jimkar the Helper folder shouldn't be there. It was required in some classes in early versions but then I changed those classes and the helper folder has been removed. If you use the latest version then you shouldn't need it.
