### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by inluxc** [ClaudiuCreanga/magento2-store-locator-stockists-extension#9]
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 50.0 MiBPHP Fatal error:  Cannot declare class Limesharp\Stockists\Block\Stores because the name is already in use in Magento2/vendor/limesharp/stockists/src/Block/Stores.php on line 28

Fatal error: Cannot declare class Limesharp\Stockists\Block\Stores because the name is already in use in Magento2/vendor/limesharp/stockists/src/Block/Stores.php on line 28

**Comment by ClaudiuCreanga** [comment]
That means you have an old version. you need to use the latest version 1.0.16
